PRESET_PRODUCTS = [
    # 1. 搬瓦工 BandwagonHost
    {
        "provider": "搬瓦工 BandwagonHost",
        "name": "LOS ANGELES - CN2 GIA ECOMMERCE (DC6)",
        "group": "CN2 GIA-E 特惠方案",
        "cpu": "2 vCPU",
        "ram": "2048 MB",
        "disk": "40 GB SSD (RAID-10)",
        "transfer": "1000 GB/月",
        "port_speed": "2.5 Gbps",
        "cpu_cores": 2,
        "ram_mb": 2048,
        "disk_gb": 40,
        "transfer_gb": 1000,
        "port_mbps": 2500,
        "regions": ["美国", "洛杉矶 DC6"],
        "lines": ["CN2 GIA", "AS9929", "CMI"],
        "status": "in_stock",
        "stock_qty": 12,
        "price": 49.99,
        "original_price": 89.99,
        "currency": "USD",
        "price_cycle": "quarterly",
        "affiliate_url": "https://bwh88.net/cart.php?a=add&pid=87",
        "stock_check_url": "https://bwh88.net/cart.php?a=add&pid=87",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 1420
    },
    {
        "provider": "搬瓦工 BandwagonHost",
        "name": "THE PLAN - 经典限时限量款 (可随心切17个机房)",
        "group": "传奇全能机型",
        "cpu": "2 vCPU",
        "ram": "2048 MB",
        "disk": "40 GB SSD",
        "transfer": "1000 GB/月",
        "port_speed": "1.0 Gbps - 2.5 Gbps",
        "cpu_cores": 2,
        "ram_mb": 2048,
        "disk_gb": 40,
        "transfer_gb": 1000,
        "port_mbps": 2500,
        "regions": ["美国", "日本", "香港", "荷兰", "加拿大"],
        "lines": ["CN2 GIA", "AS9929", "软银", "CMIN2"],
        "status": "out_of_stock",
        "stock_qty": 0,
        "price": 99.00,
        "original_price": 129.00,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://bwh88.net/cart.php?a=add&pid=129",
        "stock_check_url": "https://bwh88.net/cart.php?a=add&pid=129",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 4890
    },
    {
        "provider": "搬瓦工 BandwagonHost",
        "name": "THE PLAN v2 - 升级款 (40G SSD / 2000G 流量)",
        "group": "传奇全能机型",
        "cpu": "2 vCPU",
        "ram": "2048 MB",
        "disk": "40 GB SSD",
        "transfer": "2000 GB/月",
        "port_speed": "2.5 Gbps",
        "cpu_cores": 2,
        "ram_mb": 2048,
        "disk_gb": 40,
        "transfer_gb": 2000,
        "port_mbps": 2500,
        "regions": ["美国", "日本", "香港", "荷兰", "加拿大"],
        "lines": ["CN2 GIA", "AS9929", "软银", "CMIN2"],
        "status": "out_of_stock",
        "stock_qty": 0,
        "price": 119.00,
        "original_price": 139.00,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://bwh88.net/cart.php?a=add&pid=131",
        "stock_check_url": "https://bwh88.net/cart.php?a=add&pid=131",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 3200
    },
    {
        "provider": "搬瓦工 BandwagonHost",
        "name": "HONG KONG CN2 GIA (HKHK_8 顶级极速专线)",
        "group": "香港旗舰",
        "cpu": "2 vCPU",
        "ram": "2048 MB",
        "disk": "40 GB SSD",
        "transfer": "500 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 2,
        "ram_mb": 2048,
        "disk_gb": 40,
        "transfer_gb": 500,
        "port_mbps": 1000,
        "regions": ["香港"],
        "lines": ["CN2 GIA", "直连优化"],
        "status": "in_stock",
        "stock_qty": 3,
        "price": 89.99,
        "original_price": 89.99,
        "currency": "USD",
        "price_cycle": "monthly",
        "affiliate_url": "https://bwh88.net/cart.php?a=add&pid=66",
        "stock_check_url": "https://bwh88.net/cart.php?a=add&pid=66",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": False,
        "clicks": 680
    },
    {
        "provider": "搬瓦工 BandwagonHost",
        "name": "TOKYO CN2 GIA (JPTYO_8 日本顶级专线)",
        "group": "日本旗舰",
        "cpu": "2 vCPU",
        "ram": "2048 MB",
        "disk": "40 GB SSD",
        "transfer": "500 GB/月",
        "port_speed": "1.2 Gbps",
        "cpu_cores": 2,
        "ram_mb": 2048,
        "disk_gb": 40,
        "transfer_gb": 500,
        "port_mbps": 1200,
        "regions": ["日本", "东京"],
        "lines": ["CN2 GIA", "直连优化"],
        "status": "in_stock",
        "stock_qty": 2,
        "price": 89.99,
        "original_price": 89.99,
        "currency": "USD",
        "price_cycle": "monthly",
        "affiliate_url": "https://bwh88.net/cart.php?a=add&pid=112",
        "stock_check_url": "https://bwh88.net/cart.php?a=add&pid=112",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": False,
        "clicks": 820
    },

    # 2. RackNerd
    {
        "provider": "RackNerd",
        "name": "1.5 GB KVM VPS Special (高性价比入门款)",
        "group": "2026 特惠促销",
        "cpu": "1 vCPU",
        "ram": "1536 MB",
        "disk": "25 GB High Speed SSD",
        "transfer": "2500 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1536,
        "disk_gb": 25,
        "transfer_gb": 2500,
        "port_mbps": 1000,
        "regions": ["美国", "洛杉矶 DC02", "圣何塞", "西雅图", "芝加哥"],
        "lines": ["AS4837", "国际BGP"],
        "status": "in_stock",
        "stock_qty": 45,
        "price": 14.88,
        "original_price": 18.88,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://my.racknerd.com/cart.php?a=add&pid=801",
        "stock_check_url": "https://my.racknerd.com/cart.php?a=add&pid=801",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 3840
    },
    {
        "provider": "RackNerd",
        "name": "2.5 GB KVM VPS Special (爆款畅销主力机)",
        "group": "2026 特惠促销",
        "cpu": "2 vCPU",
        "ram": "2560 MB",
        "disk": "40 GB High Speed SSD",
        "transfer": "4000 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 2,
        "ram_mb": 2560,
        "disk_gb": 40,
        "transfer_gb": 4000,
        "port_mbps": 1000,
        "regions": ["美国", "洛杉矶 DC02", "达拉斯", "纽约", "亚特兰大"],
        "lines": ["AS4837", "国际BGP"],
        "status": "in_stock",
        "stock_qty": 20,
        "price": 20.98,
        "original_price": 25.99,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://my.racknerd.com/cart.php?a=add&pid=802",
        "stock_check_url": "https://my.racknerd.com/cart.php?a=add&pid=802",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 2900
    },
    {
        "provider": "RackNerd",
        "name": "768 MB 绝版便宜年付机 ($10.88 超低门槛)",
        "group": "限量秒杀",
        "cpu": "1 vCPU",
        "ram": "768 MB",
        "disk": "15 GB SSD",
        "transfer": "1500 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 768,
        "disk_gb": 15,
        "transfer_gb": 1500,
        "port_mbps": 1000,
        "regions": ["美国", "圣何塞", "西雅图"],
        "lines": ["国际BGP"],
        "status": "out_of_stock",
        "stock_qty": 0,
        "price": 10.88,
        "original_price": 14.88,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://my.racknerd.com/cart.php?a=add&pid=799",
        "stock_check_url": "https://my.racknerd.com/cart.php?a=add&pid=799",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 4120
    },

    # 3. DMIT
    {
        "provider": "DMIT",
        "name": "PVM.LAX.Pro.WEE (洛杉矶三网 CN2 GIA / 9929 / CMIN2)",
        "group": "Premium Pro 旗舰系列",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "10 GB SSD",
        "transfer": "450 GB/月",
        "port_speed": "500 Mbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 10,
        "transfer_gb": 450,
        "port_mbps": 500,
        "regions": ["美国", "洛杉矶"],
        "lines": ["CN2 GIA", "AS9929", "CMIN2"],
        "status": "out_of_stock",
        "stock_qty": 0,
        "price": 36.90,
        "original_price": 49.90,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://www.dmit.io/cart.php?a=add&pid=183",
        "stock_check_url": "https://www.dmit.io/cart.php?a=add&pid=183",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 5500
    },
    {
        "provider": "DMIT",
        "name": "PVM.LAX.EB.WEE (洛杉矶 CMIN2 / 4837 优化大带宽)",
        "group": "Eyeball 系列",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "15 GB SSD",
        "transfer": "1000 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 15,
        "transfer_gb": 1000,
        "port_mbps": 1000,
        "regions": ["美国", "洛杉矶"],
        "lines": ["CMIN2", "AS4837"],
        "status": "in_stock",
        "stock_qty": 6,
        "price": 39.90,
        "original_price": 49.90,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://www.dmit.io/cart.php?a=add&pid=188",
        "stock_check_url": "https://www.dmit.io/cart.php?a=add&pid=188",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 2100
    },
    {
        "provider": "DMIT",
        "name": "PVM.TYO.Pro.Pocket (日本东京 CN2 GIA)",
        "group": "Tokyo Premium Pro",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "20 GB SSD",
        "transfer": "300 GB/月",
        "port_speed": "100 Mbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 20,
        "transfer_gb": 300,
        "port_mbps": 100,
        "regions": ["日本", "东京"],
        "lines": ["CN2 GIA", "直连优化"],
        "status": "in_stock",
        "stock_qty": 5,
        "price": 18.90,
        "original_price": 21.90,
        "currency": "USD",
        "price_cycle": "monthly",
        "affiliate_url": "https://www.dmit.io/cart.php?a=add&pid=142",
        "stock_check_url": "https://www.dmit.io/cart.php?a=add&pid=142",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": False,
        "clicks": 950
    },
    {
        "provider": "DMIT",
        "name": "PVM.HKG.Pro.Pocket (香港精品 CN2 GIA 专线)",
        "group": "Hong Kong Premium",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "20 GB SSD",
        "transfer": "200 GB/月",
        "port_speed": "100 Mbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 20,
        "transfer_gb": 200,
        "port_mbps": 100,
        "regions": ["香港"],
        "lines": ["CN2 GIA", "三网极速直连"],
        "status": "in_stock",
        "stock_qty": 2,
        "price": 29.90,
        "original_price": 29.90,
        "currency": "USD",
        "price_cycle": "monthly",
        "affiliate_url": "https://www.dmit.io/cart.php?a=add&pid=131",
        "stock_check_url": "https://www.dmit.io/cart.php?a=add&pid=131",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 1820
    },

    # 4. ClawCloud
    {
        "provider": "ClawCloud",
        "name": "Hong Kong VPS 1C1G 1Gbps (香港大带宽直连)",
        "group": "VPS Special",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "20 GB NVMe",
        "transfer": "500 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 20,
        "transfer_gb": 500,
        "port_mbps": 1000,
        "regions": ["香港"],
        "lines": ["优化专线", "阿里云直连"],
        "status": "out_of_stock",
        "stock_qty": 0,
        "price": 36.00,
        "original_price": 48.00,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://claw.cloud/",
        "stock_check_url": "https://claw.cloud/cart",
        "stock_check_type": "manual",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 4900
    },
    {
        "provider": "ClawCloud",
        "name": "Japan Tokyo VPS 1C1G (日本东京 1Gbps 极速)",
        "group": "VPS Special",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "20 GB NVMe",
        "transfer": "500 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 20,
        "transfer_gb": 500,
        "port_mbps": 1000,
        "regions": ["日本", "东京"],
        "lines": ["软银", "优化直连"],
        "status": "in_stock",
        "stock_qty": 8,
        "price": 36.00,
        "original_price": 48.00,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://claw.cloud/",
        "stock_check_url": "https://claw.cloud/cart",
        "stock_check_type": "manual",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 3200
    },
    {
        "provider": "ClawCloud",
        "name": "Singapore VPS 1C1G (新加坡大带宽)",
        "group": "VPS Special",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "20 GB NVMe",
        "transfer": "500 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 20,
        "transfer_gb": 500,
        "port_mbps": 1000,
        "regions": ["新加坡"],
        "lines": ["国际BGP", "直连优化"],
        "status": "in_stock",
        "stock_qty": 14,
        "price": 36.00,
        "original_price": 48.00,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://claw.cloud/",
        "stock_check_url": "https://claw.cloud/cart",
        "stock_check_type": "manual",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": False,
        "clicks": 1800
    },

    # 5. V.PS
    {
        "provider": "V.PS",
        "name": "Tokyo Mini Pro (东京 AS9929 / CMIN2 / BBTEC软银)",
        "group": "Mini Pro 精品系列",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "15 GB NVMe SSD",
        "transfer": "600 GB/月",
        "port_speed": "500 Mbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 15,
        "transfer_gb": 600,
        "port_mbps": 500,
        "regions": ["日本", "东京"],
        "lines": ["AS9929", "CMIN2", "软银"],
        "status": "out_of_stock",
        "stock_qty": 0,
        "price": 49.95,
        "original_price": 59.95,
        "currency": "EUR",
        "price_cycle": "annually",
        "affiliate_url": "https://vps.hosting/cart.php?a=add&pid=67",
        "stock_check_url": "https://vps.hosting/cart.php?a=add&pid=67",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 2800
    },
    {
        "provider": "V.PS",
        "name": "San Jose Mini Pro (圣何塞 AS9929 / CN2 GIA)",
        "group": "Mini Pro 美西精品",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "15 GB NVMe",
        "transfer": "600 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 15,
        "transfer_gb": 600,
        "port_mbps": 1000,
        "regions": ["美国", "圣何塞"],
        "lines": ["AS9929", "CN2 GIA"],
        "status": "in_stock",
        "stock_qty": 7,
        "price": 39.95,
        "original_price": 49.95,
        "currency": "EUR",
        "price_cycle": "annually",
        "affiliate_url": "https://vps.hosting/cart.php?a=add&pid=69",
        "stock_check_url": "https://vps.hosting/cart.php?a=add&pid=69",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 1900
    },
    {
        "provider": "V.PS",
        "name": "Frankfurt Mini Pro (法兰克福 AS9929 / CN2 GIA 欧洲极速)",
        "group": "Mini Pro 欧洲精品",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "15 GB NVMe",
        "transfer": "600 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 15,
        "transfer_gb": 600,
        "port_mbps": 1000,
        "regions": ["德国", "法兰克福"],
        "lines": ["AS9929", "CN2 GIA"],
        "status": "in_stock",
        "stock_qty": 8,
        "price": 39.95,
        "original_price": 49.95,
        "currency": "EUR",
        "price_cycle": "annually",
        "affiliate_url": "https://vps.hosting/cart.php?a=add&pid=68",
        "stock_check_url": "https://vps.hosting/cart.php?a=add&pid=68",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 1400
    },

    # 6. 斯巴达 SpartanHost
    {
        "provider": "斯巴达 SpartanHost",
        "name": "Seattle KVM AMD Premium (三网4837 + 200G Cera高防秒解)",
        "group": "Premium KVM AMD",
        "cpu": "1 vCPU (AMD Ryzen 5950X)",
        "ram": "1024 MB",
        "disk": "20 GB NVMe",
        "transfer": "1000 GB/月",
        "port_speed": "10 Gbps (Burst)",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 20,
        "transfer_gb": 1000,
        "port_mbps": 10000,
        "regions": ["美国", "西雅图"],
        "lines": ["AS4837", "Cera 200G 高防"],
        "status": "out_of_stock",
        "stock_qty": 0,
        "price": 4.80,
        "original_price": 6.00,
        "currency": "USD",
        "price_cycle": "monthly",
        "affiliate_url": "https://billing.spartanhost.net/cart.php?a=add&pid=101",
        "stock_check_url": "https://billing.spartanhost.net/cart.php?a=add&pid=101",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 5100
    },

    # 7. CloudCone
    {
        "provider": "CloudCone",
        "name": "SC2 Flash Sale 1GB (洛杉矶 Multacom)",
        "group": "Flash Sale 云主机",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "30 GB SSD Cached",
        "transfer": "2000 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 30,
        "transfer_gb": 2000,
        "port_mbps": 1000,
        "regions": ["美国", "洛杉矶 DC2"],
        "lines": ["AS4837", "国际BGP"],
        "status": "in_stock",
        "stock_qty": 18,
        "price": 15.50,
        "original_price": 18.00,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://app.cloudcone.com/",
        "stock_check_url": "https://app.cloudcone.com/vps/create",
        "stock_check_type": "http_keyword",
        "out_of_stock_keyword": "Sold Out",
        "recommended": False,
        "clicks": 980
    },

    # 8. Netcup
    {
        "provider": "Netcup",
        "name": "VPS 1000 G11 (4核8G 内存超高性价比欧洲大盘)",
        "group": "G11 系列 VPS",
        "cpu": "4 vCPU",
        "ram": "8192 MB",
        "disk": "256 GB SSD",
        "transfer": "40 TB/月",
        "port_speed": "2.5 Gbps",
        "cpu_cores": 4,
        "ram_mb": 8192,
        "disk_gb": 256,
        "transfer_gb": 40000,
        "port_mbps": 2500,
        "regions": ["德国", "维也纳", "纽伦堡"],
        "lines": ["欧洲优化", "国际BGP"],
        "status": "in_stock",
        "stock_qty": 30,
        "price": 5.46,
        "original_price": 6.80,
        "currency": "EUR",
        "price_cycle": "monthly",
        "affiliate_url": "https://www.netcup.eu/",
        "stock_check_url": "https://www.netcup.eu/bestellen/produkt.php?produkt=3320",
        "stock_check_type": "http_keyword",
        "out_of_stock_keyword": "Ausverkauft",
        "recommended": True,
        "clicks": 2350
    },

    # 9. Hetzner
    {
        "provider": "Hetzner",
        "name": "CX22 Cloud (2核4G高性能云主机)",
        "group": "Cloud Server",
        "cpu": "2 vCPU",
        "ram": "4096 MB",
        "disk": "40 GB NVMe SSD",
        "transfer": "20 TB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 2,
        "ram_mb": 4096,
        "disk_gb": 40,
        "transfer_gb": 20000,
        "port_mbps": 1000,
        "regions": ["德国", "芬兰", "美国", "弗吉尼亚", "俄勒冈"],
        "lines": ["国际BGP", "欧美骨干网"],
        "status": "in_stock",
        "stock_qty": 99,
        "price": 3.79,
        "original_price": 3.79,
        "currency": "EUR",
        "price_cycle": "monthly",
        "affiliate_url": "https://www.hetzner.com/cloud",
        "stock_check_url": "https://www.hetzner.com/cloud",
        "stock_check_type": "manual",
        "out_of_stock_keyword": "Sold Out",
        "recommended": True,
        "clicks": 2700
    },

    # 10. BuyVM (Frantech)
    {
        "provider": "BuyVM (Frantech)",
        "name": "Las Vegas 1GB Slice (不限流量 + 可挂载廉价存储块)",
        "group": "KVM Slices",
        "cpu": "1 vCPU (Ryzen 3900X)",
        "ram": "1024 MB",
        "disk": "20 GB NVMe",
        "transfer": "无限流量",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 20,
        "transfer_gb": 99999,
        "port_mbps": 1000,
        "regions": ["美国", "拉斯维加斯", "纽约", "迈阿密", "卢森堡"],
        "lines": ["国际BGP", "抗DMCA(卢森堡)"],
        "status": "out_of_stock",
        "stock_qty": 0,
        "price": 3.50,
        "original_price": 3.50,
        "currency": "USD",
        "price_cycle": "monthly",
        "affiliate_url": "https://my.frantech.ca/cart.php?a=add&pid=1426",
        "stock_check_url": "https://my.frantech.ca/cart.php?a=add&pid=1426",
        "stock_check_type": "whmcs",
        "out_of_stock_keyword": "Out of Stock",
        "recommended": True,
        "clicks": 3400
    },

    # 11. AkileCloud
    {
        "provider": "AkileCloud",
        "name": "HKPro-One (香港三网直连大带宽 1Gbps)",
        "group": "Pro 直连专线",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "10 GB NVMe",
        "transfer": "1000 GB/月",
        "port_speed": "1 Gbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 10,
        "transfer_gb": 1000,
        "port_mbps": 1000,
        "regions": ["香港"],
        "lines": ["三网直连", "流媒体解锁"],
        "status": "in_stock",
        "stock_qty": 11,
        "price": 19.99,
        "original_price": 24.99,
        "currency": "CNY",
        "price_cycle": "monthly",
        "affiliate_url": "https://akile.io/",
        "stock_check_url": "https://akile.io/",
        "stock_check_type": "manual",
        "out_of_stock_keyword": "缺货",
        "recommended": True,
        "clicks": 2650
    },

    # 12. WikiHost 微基主机
    {
        "provider": "WikiHost 微基主机",
        "name": "香港 BGP 优化一期 (大带宽 500Mbps)",
        "group": "香港优化系列",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "25 GB NVMe",
        "transfer": "800 GB/月",
        "port_speed": "500 Mbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 25,
        "transfer_gb": 800,
        "port_mbps": 500,
        "regions": ["香港"],
        "lines": ["直连优化", "BGP优化"],
        "status": "out_of_stock",
        "stock_qty": 0,
        "price": 35.00,
        "original_price": 45.00,
        "currency": "CNY",
        "price_cycle": "monthly",
        "affiliate_url": "https://idc.wiki/",
        "stock_check_url": "https://idc.wiki/",
        "stock_check_type": "manual",
        "out_of_stock_keyword": "缺货",
        "recommended": True,
        "clicks": 1780
    },

    # 13. Kurun 库润
    {
        "provider": "Kurun 库润",
        "name": "Los Angeles CN2 GIA / 9929 (中国优化专线机房)",
        "group": "精品直连专线",
        "cpu": "1 vCPU",
        "ram": "1024 MB",
        "disk": "20 GB SSD",
        "transfer": "500 GB/月",
        "port_speed": "200 Mbps",
        "cpu_cores": 1,
        "ram_mb": 1024,
        "disk_gb": 20,
        "transfer_gb": 500,
        "port_mbps": 200,
        "regions": ["美国", "洛杉矶"],
        "lines": ["CN2 GIA", "AS9929"],
        "status": "in_stock",
        "stock_qty": 7,
        "price": 28.00,
        "original_price": 35.00,
        "currency": "USD",
        "price_cycle": "annually",
        "affiliate_url": "https://www.kurun.com/",
        "stock_check_url": "https://www.kurun.com/cart",
        "stock_check_type": "manual",
        "out_of_stock_keyword": "无库存",
        "recommended": False,
        "clicks": 540
    }
]
